apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: demo-gitops
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: html-volume
          configMap:
            name: httpd-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-html
  namespace: demo-gitops
data:
  index.html: |
    <html>
    <head><title>Hello from Apache in Kubernetes</title></head>
    <body>
      <h1>Welcome to Apache HTTP Server running in Kubernetes!</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: demo-gitops
spec:
  type: LoadBalancer
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

